---
- name: This is a first playbook
  hosts: all
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.file:
        path: /tmp/test{1..9}.mp3  
        state: touch

    - name: Copy file with owner and permissions
      ansible.builtin.package:
        name: httpd 
        state: absent    
    

