---
- name: This is a first playbook
  hosts: all
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.file:
        path: /tmp/test{1..9}.mp3  
        state: present

    - name: Copy file with owner and permissions
      ansible.builtin.package:
        name: tree  
        state: present    
    

