---
- name: This is a first playbook
  hosts: all
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.file:
        path: /tmp/test1.mp3  
        state: absent 
    

